name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cypress tests
        uses: cypress-io/github-action@v7
        with:
          start: python3 -m http.server 5500 --directory app
          wait-on: http://127.0.0.1:5500/app
          wait-on-timeout: 120
          browser: chrome